name: Push Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - run: |
        cd translate
        git config --global url."https://github".insteadOf git://github
        pip install -r requirements.txt
        ./gen_rc.sh
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: translate
        path: translate/generated/translate.rc
        if-no-files-found: error
    - run: |
        mkdir .nuget
        cd .nuget
        curl -OL https://github.com/ysc3839/GitInfo/releases/download/v2.0.33/GitInfo.2.0.33.nupkg
        nuget sources add -name gitinfo -source `cygpath -wa .`
        cd ..
        nuget restore ClashXW.sln
      shell: bash
    - run: |
        vcpkg install skyr-url --triplet=x64-windows-static
        vcpkg integrate install
      shell: cmd
    - run: |
        Start-Job -Init ([ScriptBlock]::Create("Set-Location '$pwd'")) -Script {
          msbuild ClashXW.sln "-p:Configuration=Release;Platform=x64" }
        Get-Job | Wait-Job | Receive-Job
      shell: powershell
    - uses: actions/upload-artifact@v3
      with:
        name: ClashXW64
        path: x64/Release/ClashXW64.exe
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: ClashXW64
        path: x64/Release/ClashXW64.pdb
        if-no-files-found: error
